# Generated by Django 5.1.7 on 2025-04-02 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Errores_agravante",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_error", models.CharField(max_length=100)),
                ("nota", models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("nota_final", models.DecimalField(decimal_places=2, max_digits=3)),
                ("clasificacion", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Pilares",
            fields=[
                ("id_pilar", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Registro_materialidad",
            fields=[
                ("id_registro", models.AutoField(primary_key=True, serialize=False)),
                ("rut", models.CharField(max_length=12)),
                ("dv", models.CharField(max_length=1)),
                ("log_fecha_registro", models.CharField(max_length=20)),
                ("login_creador", models.CharField(max_length=100)),
                ("nombre_creador", models.CharField(max_length=100)),
                ("oficina_ejecutivo", models.CharField(max_length=100)),
                ("cui", models.CharField(max_length=20)),
                ("etapa_venta_actual", models.CharField(max_length=100)),
                ("inconsistencia", models.CharField(max_length=100)),
                ("monto_oferta", models.CharField(max_length=100)),
                ("proceso_credito", models.CharField(max_length=100)),
                ("pauta_evaluacion", models.CharField(max_length=100)),
                ("decision_final", models.CharField(max_length=100)),
                ("ano_mes", models.CharField(max_length=6)),
                ("canal", models.CharField(max_length=100)),
                ("prod_eval", models.CharField(max_length=100)),
                ("nombre_ejecutivo", models.CharField(max_length=100)),
                ("rut_ejecutivo", models.CharField(max_length=12)),
                ("mes_numero", models.CharField(max_length=12)),
                ("mes_nombre", models.CharField(max_length=20)),
                ("codigo_suc", models.CharField(max_length=10)),
                ("nombre_suc", models.CharField(max_length=100)),
                ("aprobador", models.CharField(max_length=100)),
                ("n_oportunidad", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Parametro",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=150)),
                (
                    "errores_agravantes",
                    models.ManyToManyField(blank=True, to="ficha.errores_agravante"),
                ),
                (
                    "pilar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ficha.pilares"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "errores_agravantes",
                    models.ManyToManyField(blank=True, to="ficha.errores_agravante"),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ficha.evaluacion",
                    ),
                ),
                (
                    "parametro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ficha.parametro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roles", models.CharField(max_length=50)),
                (
                    "foto",
                    models.ImageField(default="default.jpg", upload_to="static/img"),
                ),
                ("ci", models.CharField(max_length=10, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
