# Generated by Django 5.1.7 on 2025-05-08 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="evaluacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="depuracion_antecedentes",
                to="ficha.evaluacion",
            ),
        ),
        migrations.AlterField(
            model_name="evaluacionformalidad",
            name="evaluacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formalidad",
                to="ficha.evaluacion",
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciongestionotorga",
            name="evaluacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gestion_otorga",
                to="ficha.evaluacion",
            ),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="evaluacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingreso_datos",
                to="ficha.evaluacion",
            ),
        ),
    ]
