# Generated by Django 5.1.7 on 2025-04-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registro_materialidad",
            old_name="decision_final",
            new_name="estado",
        ),
        migrations.RenameField(
            model_name="registro_materialidad",
            old_name="n_oportunidad",
            new_name="id_oportunidad",
        ),
        migrations.RenameField(
            model_name="registro_materialidad",
            old_name="nombre_creador",
            new_name="max_prod_rgo",
        ),
        migrations.RemoveField(
            model_name="registro_materialidad",
            name="mes_numero",
        ),
    ]
