# Generated by Django 5.1.7 on 2025-05-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0002_alter_evaluaciondepuracionantecedentes_evaluacion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evaluaciondepuracionantecedentes",
            old_name="evaluacion",
            new_name="id_evaluacion",
        ),
        migrations.RenameField(
            model_name="evaluacionformalidad",
            old_name="evaluacion",
            new_name="id_evaluacion",
        ),
        migrations.RenameField(
            model_name="evaluaciongestionotorga",
            old_name="evaluacion",
            new_name="id_evaluacion",
        ),
        migrations.RenameField(
            model_name="evaluacioningresodedatos",
            old_name="evaluacion",
            new_name="id_evaluacion",
        ),
    ]
