# Generated by Django 5.1.7 on 2025-04-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0002_rename_decision_final_registro_materialidad_estado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parametro",
            name="errores_agravantes",
        ),
        migrations.RemoveField(
            model_name="parametro",
            name="pilar",
        ),
        migrations.RemoveField(
            model_name="detalleevaluacion",
            name="parametro",
        ),
        migrations.DeleteModel(
            name="Pilares",
        ),
        migrations.DeleteModel(
            name="Parametro",
        ),
    ]
