# Generated by Django 5.1.7 on 2025-05-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ficha",
            "0003_rename_evaluacion_evaluaciondepuracionantecedentes_id_evaluacion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="observacion_tipo_renta",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
