# Generated by Django 5.1.7 on 2025-05-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0003_alter_evaluacion_clasificacion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detalle_evaluaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_sucursal", models.IntegerField(unique=True)),
                ("nombre_sucursal", models.CharField(max_length=100)),
                (
                    "promedio_notas",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "nota_automatica",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "nota_final",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "clasificacion_final",
                    models.CharField(default="Sin clasificar", max_length=15),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
