# Generated by Django 5.1.7 on 2025-05-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0004_detalle_evaluaciones"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detalle_evaluaciones",
            name="id",
        ),
        migrations.AlterField(
            model_name="detalle_evaluaciones",
            name="codigo_sucursal",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
