# Generated by Django 5.1.7 on 2025-04-24 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0004_remove_evaluacion_id_evaluacion_id_evaluacion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evaluacioningresodedatos",
            name="tipo_renta",
        ),
        migrations.AddField(
            model_name="evaluacionformalidad",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evaluacioningresodedatos",
            name="observacion_tipo_renta",
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
