# Generated by Django 5.1.7 on 2025-05-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0004_alter_evaluacioningresodedatos_observacion_tipo_renta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evaluaciondepuracionantecedentes",
            name="user",
        ),
        migrations.RemoveField(
            model_name="evaluacionformalidad",
            name="user",
        ),
        migrations.RemoveField(
            model_name="evaluaciongestionotorga",
            name="user",
        ),
        migrations.RemoveField(
            model_name="evaluacioningresodedatos",
            name="user",
        ),
    ]
