# Generated by Django 5.1.7 on 2025-05-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0005_remove_evaluaciondepuracionantecedentes_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registro_materialidad",
            fields=[
                ("id_registro", models.AutoField(primary_key=True, serialize=False)),
                ("rut", models.CharField(max_length=12)),
                ("dv", models.CharField(max_length=1)),
                ("log_fecha_registro", models.CharField(max_length=20)),
                ("login_creador", models.CharField(max_length=100)),
                ("nombre_ejecutivo", models.CharField(max_length=100)),
                ("rut_ejecutivo", models.CharField(max_length=12)),
                ("oficina_ejecutivo", models.CharField(max_length=100)),
                ("cui", models.CharField(max_length=20)),
                ("etapa_venta_actual", models.CharField(max_length=100)),
                ("inconsistencia", models.CharField(max_length=100)),
                ("max_prod_rgo", models.CharField(max_length=100)),
                ("monto_oferta", models.CharField(max_length=100)),
                ("proceso_credito", models.CharField(max_length=100)),
                ("pauta_evaluacion", models.CharField(max_length=100)),
                ("ano_mes", models.CharField(max_length=6)),
                ("canal", models.CharField(max_length=100)),
                ("prod_eval", models.CharField(max_length=100)),
                ("mes_nombre", models.CharField(max_length=20)),
                ("estado", models.CharField(max_length=100)),
                ("codigo_suc", models.CharField(max_length=10)),
                ("nombre_suc", models.CharField(max_length=100)),
                ("aprobador", models.CharField(max_length=100)),
                ("id_oportunidad", models.CharField(max_length=20)),
            ],
        ),
    ]
