# Generated by Django 5.1.7 on 2025-06-03 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0005_remove_detalle_evaluaciones_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraficoGenerado",
            fields=[
                ("id_grafico", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            (
                                "distribucion_calificaciones",
                                "Distribución de Calificaciones",
                            ),
                            ("cumplimiento_por_pilar", "Cumplimiento por Pilar"),
                            ("otros", "Otros"),
                        ],
                        max_length=50,
                    ),
                ),
                ("imagen", models.ImageField(upload_to="graficos/")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "informe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graficos",
                        to="ficha.detalle_evaluaciones",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                ("id_reporte", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_reporte", models.CharField(max_length=100)),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                ("archivo_pdf", models.FileField(upload_to="informes/")),
                (
                    "detalle_sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ficha.detalle_evaluaciones",
                    ),
                ),
            ],
        ),
    ]
