# Generated by Django 5.1.7 on 2025-04-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0005_remove_evaluacioningresodedatos_tipo_renta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluacion",
            name="tipo_cliente",
            field=models.CharField(blank=True, default=1, max_length=10),
        ),
    ]
