# Generated by Django 5.1.7 on 2025-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0006_evaluacion_tipo_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluacion",
            name="tipo_cliente",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Prospecto", "prospecto"),
                    ("Nuevo", "nuevo"),
                    ("Antiguo", "antiguo"),
                    ("Plus", "plus"),
                ],
                default=1,
                max_length=10,
            ),
        ),
    ]
