# Generated by Django 5.1.7 on 2025-06-05 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0006_graficogenerado_reporte"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalle_evaluaciones",
            name="evaluacion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalle_eva",
                to="ficha.evaluacion",
            ),
            preserve_default=False,
        ),
    ]
