# Generated by Django 5.1.7 on 2025-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0007_alter_evaluacion_tipo_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluacion",
            name="fecha",
            field=models.DateField(),
        ),
    ]
