# Generated by Django 5.1.7 on 2025-05-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0007_tipo_errores_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tipo_errores",
        ),
    ]
