# Generated by Django 5.1.7 on 2025-06-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0007_detalle_evaluaciones_evaluacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detalle_evaluaciones",
            name="evaluacion",
        ),
    ]
