# Generated by Django 5.1.7 on 2025-04-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0008_alter_evaluacion_fecha"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evaluacionformalidad",
            name="evaluacion",
        ),
        migrations.RemoveField(
            model_name="evaluacionformalidad",
            name="id",
        ),
        migrations.AddField(
            model_name="evaluacionformalidad",
            name="evaluador",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="evaluacionformalidad",
            name="id_formalidad",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
