# Generated by Django 5.1.7 on 2025-05-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0008_delete_tipo_errores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluacionformalidad",
            name="tipo_error_acreditacion_ingresos",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="evaluacionformalidad",
            name="tipo_error_estado_situacion",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="evaluacionformalidad",
            name="tipo_error_verificacion_laboral",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
