# Generated by Django 5.1.7 on 2025-04-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0009_remove_evaluacionformalidad_evaluacion_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EvaluacionFormalidad",
        ),
    ]
