# Generated by Django 5.1.7 on 2025-05-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ficha",
            "0010_alter_evaluacionformalidad_tipo_error_acreditacion_ingresos_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="errores_agravante",
            name="item",
            field=models.CharField(
                choices=[
                    ("verificacion_laboral", "Verificación Laboral"),
                    ("estado_situacion", "Estado de Situación"),
                    ("acreditacion_ingresos", "Acreditación de Ingresos"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
