# Generated by Django 5.1.7 on 2025-04-28 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0010_delete_evaluacionformalidad"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluacionFormalidad",
            fields=[
                ("id_formalidad", models.AutoField(primary_key=True, serialize=False)),
                (
                    "respuesta_verificacion_laboral",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sin-error", "Sin Error"),
                            ("error", "Error"),
                            ("n/a", "N/A"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_error_verificacion_laboral",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "observacion_verificacion",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "respuesta_estado_situacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sin-error", "Sin Error"),
                            ("error", "Error"),
                            ("n/a", "N/A"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_error_estado_situacion",
                    models.CharField(blank=True, max_length=50),
                ),
                ("observacion_estado", models.CharField(blank=True, max_length=100)),
                (
                    "respuesta_acreditacion_ingresos",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sin-error", "Sin Error"),
                            ("error", "Error"),
                            ("n/a", "N/A"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_error_acreditacion_ingresos",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "observacion_acreditacion",
                    models.CharField(blank=True, max_length=100),
                ),
                ("evaluador", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
