# Generated by Django 5.1.7 on 2025-05-19 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0011_errores_agravante_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errores_agravante",
            name="item",
            field=models.CharField(
                choices=[
                    ("verificacion_laboral", "Verificación Laboral"),
                    ("estado_situacion", "Estado de Situación"),
                    ("acreditacion_ingresos", "Acreditación de Ingresos"),
                    ("condiciones_aprobacion", "Condiciones Aprobacion"),
                    ("cambio_evaAT", "Cambio Evaluacion AT"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="respuesta_activo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="respuesta_arriendos",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="respuesta_cuota_cp",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="respuesta_cuota_ooii",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="respuesta_cuota_prestamo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="respuesta_dividendo_BCH",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="respuesta_ingresos_mensuales",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="respuesta_monto_compra_cp",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="respuesta_monto_compra_lp",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="respuesta_monto_compra_ooii",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="respuesta_monto_compra_sbif",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="respuesta_otros_egre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="respuesta_renegociado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacionformalidad",
            name="respuesta_acreditacion_ingresos",
            field=models.CharField(
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacionformalidad",
            name="respuesta_estado_situacion",
            field=models.CharField(
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciongestionotorga",
            name="respuesta_atribuciones",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciongestionotorga",
            name="respuesta_cambio_evaAT",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciongestionotorga",
            name="respuesta_condiciones_aprobacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciongestionotorga",
            name="respuesta_contribucion_garantia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciongestionotorga",
            name="respuesta_deudas_vinculadas",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciongestionotorga",
            name="tipo_error_cambio_evaAT",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="errores_cambio_evaAT",
                to="ficha.errores_agravante",
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciongestionotorga",
            name="tipo_error_condiciones_aprobacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="errores_condiciones_aprobacion",
                to="ficha.errores_agravante",
            ),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="respuesta_actividad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="respuesta_carrera_semestre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="respuesta_direccion_part",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="respuesta_estado_civil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="respuesta_fecha_in_empleo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="respuesta_nacionalidad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="respuesta_nivel_educa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="respuesta_profesion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="respuesta_tipo_contrato",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="respuesta_tipo_renta",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="respuesta_universidad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Error", "sin error"),
                    ("Error", "error"),
                    ("N/A", "n/a"),
                ],
                max_length=10,
            ),
        ),
    ]
