# Generated by Django 5.1.7 on 2025-05-19 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0012_alter_errores_agravante_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluaciondepuracionantecedentes",
            name="tipo_error_ingresos_mensuales",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ingresos_mensuales",
                to="ficha.errores_agravante",
            ),
        ),
        migrations.AddField(
            model_name="evaluaciongestionotorga",
            name="tipo_error_atribuciones",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="errores_atribuciones",
                to="ficha.errores_agravante",
            ),
        ),
        migrations.AddField(
            model_name="evaluaciongestionotorga",
            name="tipo_error_contribucion_garantia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="errores_contribucion_garantia",
                to="ficha.errores_agravante",
            ),
        ),
        migrations.AlterField(
            model_name="errores_agravante",
            name="item",
            field=models.CharField(
                choices=[
                    ("verificacion_laboral", "Verificación Laboral"),
                    ("estado_situacion", "Estado de Situación"),
                    ("acreditacion_ingresos", "Acreditación de Ingresos"),
                    ("error_atribuciones", "Atribuciones"),
                    ("contribucion_garantia", "Constitución Garantías y/o Aval"),
                    ("condiciones_aprobacion", "Condiciones Aprobación"),
                    ("cambio_evaAT", "Cambio Evaluación AT"),
                    ("ingresos_mensuales", "Ingresos Mensuales"),
                    (
                        "monto_renegociado",
                        "Monto a Reestructurar Renegociado Corto Plazo y/o Largo Plazo",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
