# Generated by Django 5.1.7 on 2025-05-19 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ficha",
            "0013_evaluaciondepuracionantecedentes_tipo_error_ingresos_mensuales_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluaciondepuracionantecedentes",
            name="tipo_error_monto_renegociado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monto_renegociado",
                to="ficha.errores_agravante",
            ),
        ),
    ]
