# Generated by Django 5.1.7 on 2025-05-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0014_evaluaciondepuracionantecedentes_tipo_error_monto_renegociado"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluacion",
            name="cantidad_errores",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
