# Generated by Django 5.1.7 on 2025-05-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0015_evaluacion_cantidad_errores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluacion",
            name="nota_final",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
