# Generated by Django 5.1.7 on 2025-05-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0016_alter_evaluacion_nota_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluacion",
            name="clasificacion",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="evaluacion",
            name="nota_final",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="observacion_activo",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="observacion_arriendos",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="observacion_cuota_cp",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="observacion_cuota_ooii",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="observacion_cuota_prestamo",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="observacion_dividendo_BCH",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="observacion_monto_compra_cp",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="observacion_monto_compra_lp",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="observacion_monto_compra_ooii",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="observacion_monto_compra_sbif",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="observacion_otros_egre",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluaciondepuracionantecedentes",
            name="observacion_renegociado",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluacionformalidad",
            name="observacion_acreditacion",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluacionformalidad",
            name="observacion_estado",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluacionformalidad",
            name="observacion_verificacion",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluaciongestionotorga",
            name="observacion_cambioEva",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluaciongestionotorga",
            name="observacion_condicion_aprob",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluaciongestionotorga",
            name="observacion_res_deuda_vincu",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluaciongestionotorga",
            name="observaciones_contribucion_garantia",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluaciongestionotorga",
            name="observaciones_revision_credito",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="observacion_actividad",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="observacion_carrera_semestre",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="observacion_direccion_part",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="observacion_estado_civil",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="observacion_fecha_in_empleo",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="observacion_nacionalidad",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="observacion_nivel_educa",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="observacion_profesion",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="observacion_tipo_contrato",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="observacion_tipo_renta",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="evaluacioningresodedatos",
            name="observacion_universidad",
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
