# Generated by Django 5.1.7 on 2025-05-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0017_alter_evaluacion_clasificacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluaciondepuracionantecedentes",
            name="corresponde_compra_cartera",
            field=models.BooleanField(
                default=False, verbose_name="¿Corresponde compra cartera?"
            ),
        ),
    ]
