# Generated by Django 5.1.7 on 2025-05-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0018_evaluaciondepuracionantecedentes_corresponde_compra_cartera"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evaluaciongestionotorga",
            old_name="observaciones_revision_credito",
            new_name="observaciones_atribuciones",
        ),
    ]
