# Generated by Django 5.1.7 on 2025-05-23 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ficha",
            "0019_rename_observaciones_revision_credito_evaluaciongestionotorga_observaciones_atribuciones",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="evaluaciongestionotorga",
            old_name="observaciones_contribucion_garantia",
            new_name="observaciones_cconstitucion_garantia",
        ),
        migrations.RenameField(
            model_name="evaluaciongestionotorga",
            old_name="respuesta_contribucion_garantia",
            new_name="respuesta_constitucion_garantia",
        ),
        migrations.RemoveField(
            model_name="evaluaciongestionotorga",
            name="tipo_error_contribucion_garantia",
        ),
        migrations.AddField(
            model_name="evaluaciongestionotorga",
            name="tipo_error_constitucion_garantia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="errores_constitucion_garantia",
                to="ficha.errores_agravante",
            ),
        ),
        migrations.AlterField(
            model_name="errores_agravante",
            name="item",
            field=models.CharField(
                choices=[
                    ("verificacion_laboral", "Verificación Laboral"),
                    ("estado_situacion", "Estado de Situación"),
                    ("acreditacion_ingresos", "Acreditación de Ingresos"),
                    ("error_atribuciones", "Atribuciones"),
                    ("constitucion_garantia", "Constitución Garantías y/o Aval"),
                    ("condiciones_aprobacion", "Condiciones Aprobación"),
                    ("cambio_evaAT", "Cambio Evaluación AT"),
                    ("ingresos_mensuales", "Ingresos Mensuales"),
                    (
                        "monto_renegociado",
                        "Monto a Reestructurar Renegociado Corto Plazo y/o Largo Plazo",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
