# Generated by Django 5.1.7 on 2025-05-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ficha",
            "0020_rename_observaciones_contribucion_garantia_evaluaciongestionotorga_observaciones_cconstitucion_garan",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="evaluaciongestionotorga",
            old_name="observaciones_cconstitucion_garantia",
            new_name="observaciones_constitucion_garantia",
        ),
    ]
