# Generated by Django 5.1.7 on 2025-05-26 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ficha",
            "0022_remove_evaluaciondepuracionantecedentes_obs_activo_debe_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluacion",
            name="codigo_sucursal",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(999999999999999)],
            ),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="login_ejecutivo",
            field=models.CharField(default="Login no encontrado", max_length=50),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="monto_solicitado",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="nombre_ejecutivo",
            field=models.CharField(default="Nombre no encontrado", max_length=100),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="proceso_credito",
            field=models.CharField(
                default="Tipo de credito no encontrado", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="producto",
            field=models.CharField(default="Producto no encontrado", max_length=100),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="rut",
            field=models.CharField(default="Rut no registrado", max_length=12),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="sucursal",
            field=models.CharField(default="Sucursal no encontrada", max_length=100),
        ),
    ]
