# Generated by Django 5.1.7 on 2025-05-26 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0023_evaluacion_codigo_sucursal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluacion",
            name="monto_solicitado",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(99999999999999999999)
                ],
            ),
        ),
    ]
