# Generated by Django 5.1.7 on 2025-05-26 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0024_alter_evaluacion_monto_solicitado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluacion",
            name="monto_solicitado",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(999999999999999)],
            ),
        ),
    ]
