# Generated by Django 5.1.7 on 2025-05-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0025_alter_evaluacion_monto_solicitado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluacion",
            name="monto_solicitado",
            field=models.CharField(default="Monto no encontrado ", max_length=20),
        ),
    ]
