# Generated by Django 5.1.7 on 2025-05-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0026_alter_evaluacion_monto_solicitado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evaluacion",
            old_name="nombre_ejecutivo",
            new_name="nombre_ejec",
        ),
        migrations.AlterField(
            model_name="evaluacion",
            name="monto_solicitado",
            field=models.CharField(default="Monto no encontrado", max_length=20),
        ),
    ]
