# Generated by Django 5.1.7 on 2025-05-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ficha", "0027_rename_nombre_ejecutivo_evaluacion_nombre_ejec_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evaluacion",
            old_name="rut",
            new_name="rut_cliente",
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="rut_ejec",
            field=models.CharField(default="Rut no registrado", max_length=12),
        ),
        migrations.AlterField(
            model_name="registro_materialidad",
            name="nombre_suc",
            field=models.CharField(max_length=300),
        ),
    ]
